### ISSUE TITLE
Feature: Show maker in trade history

### ISSUE THREAD

**Issue by davidkzeng** [skynetcap/serum-data#57]
**Background:**
Currently the Trade History window shows price, quantity and taker.

**Feature Idea:**
Add a maker column to the trade history window. 

**Additional Solution Notes:**
Useful to see which makers are actually getting filled.

**Comment by skynetcap** [comment]
Thanks for the submission. This will be prioritized.

**Comment by skynetcap** [comment]
Linear: SRM-84
