### ISSUE TITLE
Feature: Allow copying of full market pubkey

### ISSUE THREAD

**Issue by riordanp** [skynetcap/serum-data#83]
**Feature Idea:**
Please add the ability to copy the full market public key, as well as potentially the bids/asks keys and event queue. Showing lot sizes somewhere could also be cool. Maybe an 'Advanced Info' kind of pane that doesn't need to be shown by default. Would find this very useful as a dev.

**Comment by skynetcap** [comment]
Thanks for the request, will prioritize.

**Comment by skynetcap** [comment]
Market details (including pubkeys) deployed to production with #90.
![image](https://user-images.githubusercontent.com/100323448/181155789-3351c0d9-20b6-4d75-9b26-3a6339491447.png)
